more explanation and examples for setup-game.sh script
UNSWComputing/rUNSWift-docs pull request #21
Opened 2020-10-24 07:04 UTC by CarlinWilliamson

We had _issues_ running a practise game today due to user error with this script...

Added an example usage and more hints about the syntax

2020-10-24 07:36 UTC, jayenashar commented
can we add the examples to `setup-game.config.sh` as comments?

please note that the intention now is for the config is committed to git, to keep a record of practice and real games.

2020-10-24 08:11 UTC, pzrq requested changes
Great start.

I think we can have this and also follow Jayen’s suggestion if time allows - others need not wait until code release for human-readable documentation updates.

2020-10-24 08:11 UTC, pzrq commented on source/game_preparation/setup_game_script.rst
> +    To setup two teams enter space seperated values (no commas).
Typo: Make it “separated”

2020-10-24 08:11 UTC, pzrq commented on source/game_preparation/setup_game_script.rst
> +    For example, two teams might be configures as such:
Grammar: “configured”

2020-10-24 08:12 UTC, pzrq commented
@abhivij If you have suggestions as you also learnt this with us today, we’d also be happy to hear them 😄

2020-10-24 12:40 UTC, CarlinWilliamson commented on source/game_preparation/setup_game_script.rst
> +    To setup two teams enter space seperated values (no commas).
```suggestion
    To setup two teams enter space separated values (no commas).
```
I can't spell to save my life XD

2020-10-24 12:40 UTC, CarlinWilliamson commented on source/game_preparation/setup_game_script.rst
> +    For example, two teams might be configures as such:
```suggestion
    For example, two teams might be configured as such: 
```

2020-10-24 12:51 UTC, CarlinWilliamson commented
> can we add the examples to `setup-game.config.sh` as comments?
> 
> please note that the intention now is for the config is committed to git, to keep a record of practice and real games.

We could but adding another example to that file will have `setup-game.sh` the actual and example which could lead to more confusion.
Another option would be to have a practise game setup as the default values but this could lead to some interesting accidents at competition.

2020-10-24 13:57 UTC, CarlinWilliamson commented
> > can we add the examples to `setup-game.config.sh` as comments?
> > please note that the intention now is for the config is committed to git, to keep a record of practice and real games.
> 
> We could but adding another example to that file will have `setup-game.sh` the actual and example which could lead to more confusion.
> Another option would be to have a practise game setup as the default values but this could lead to some interesting accidents at competition.

Kindof poor excuse isn't it...
Here is a [PR](https://github.com/UNSWComputing/rUNSWift/pull/2400) which adds the second example to `setup-game.config.sh`

2020-10-24 18:54 UTC, jayenashar commented
> We could but adding another example to that file will have `setup-game.sh` the actual and example which could lead to more confusion.

Leave it commented out

> Another option would be to have a practise game setup as the default values but this could lead to some interesting accidents at competition.

If you commit every practice/competition game, it's less of an issue.

2020-10-26 09:59 UTC, pzrq approved these changes
Looks good to me

I’d be inclined not to overthink it, different team members will have different communication preferences and styles and that’s generally to be celebrated.

2020-10-30 07:02 UTC, merged

2020-10-30 07:02 UTC, pzrq commented
Happy to handle any further feedback in future PRs 😄